version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Samara
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: Europe/Samara
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Samara
    labels:
      - dependencies
      - ci
